{
 "title": "Terra",
 "description": "Dashboards for displaying accelerate metrics for DSP",
 "time": { "from": "now-7d", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "environment",
    "label": "environment",
    "query": {
     "query": "label_values(sherlock_deploy_frequency, environment)"
    }
   }
  ]
 },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 14, "w": 24, "x": 0, "y": 0 },
   "options": {
    "content": "# This dashboard is going away! The data here should be considered inaccurate from January 12th 2023 onward.\n\n# The newer replacement is available [here](https://grafana.dsp-devops.broadinstitute.org/d/Uh_BPk2Vz/v2-accelerate-metrics-per-environment)\n\nThe newer dashboard is based on Sherlock's newer API, letting DevOps eventually remove this one's older API so we can roll out features it isn't compatible with.\n\nFeel free to drop any feedback or suggestions in [#dsp-dashboards](https://broadinstitute.slack.com/archives/C02M64AJWGK)!"
   }
  },
  {
   "title": "Total Number of Deployments (Past 7 Days)",
   "type": "stat",
   "description": "The number of deploy events across all services in an environment over the past 7 days",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 14 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(sherlock_deploy_frequency{environment=\"$environment\"}[7d]))"
    }
   ]
  },
  {
   "title": "Average Lead Time (Past 7 Days)",
   "type": "stat",
   "description": "Average lead time for a change to reach a given environment over the past 7 days",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "h" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(sherlock_lead_time_to_environment{environment=\"$environment\",service!~\"agora|firecloudui|thurloe\"}) / count(sherlock_lead_time_to_environment{environment=\"$environment\",service!~\"agora|firecloudui|thurloe\"})"
    }
   ]
  },
  {
   "title": "Deploy Count by Service (Past 7 days)",
   "type": "bargauge",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 22 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (service) (increase(sherlock_deploy_frequency{environment=\"$environment\"}[7d]))",
     "legendFormat": "{{service}}"
    }
   ]
  },
  {
   "title": "Deploy Timeline by Service",
   "type": "state-timeline",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 32 },
   "targets": [
    {
     "expr": "sum by (service) (increase(sherlock_deploy_frequency{environment=\"$environment\"}[2h]))",
     "legendFormat": "{{service}}"
    }
   ]
  },
  {
   "title": "Lead Time by Service",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "h" } },
   "targets": [
    {
     "expr": "sherlock_lead_time_to_environment{environment=\"$environment\",service!~\"agora|firecloudui|thurloe\"}",
     "legendFormat": "{{service}}"
    }
   ]
  }
 ]
}